# Generated by Django 6.0.2 on 2026-02-07 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Emprendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tienda', models.CharField(max_length=100)),
                ('rubro', models.CharField(help_text='Ej: Productos Capilares o Zapatillas', max_length=100)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('imagen_url', models.URLField(blank=True, help_text='https://scontent.faep9-1.fna.fbcdn.net/v/t39.30808-6/626296689_930160152691896_2706499633103076282_n.jpg?stp=cp6_dst-jpg_tt6&_nc_cat=102&ccb=1-7&_nc_sid=833d8c&_nc_eui2=AeFzF1LwmrYqUrYoQcbzXa1H0abh7oTzaOHRpuHuhPNo4cS37fzFj2ennXQizIRP8xj91Aer7-BOmZnmJGDDMlB-&_nc_ohc=X79gSPWwkX4Q7kNvwFjNrol&_nc_oc=AdktSAgzHFpDNhKlcg-pzkMtoF4zqn9idIw-V2jF-Yg48lMnrNWUNe4JDl6te5RpYNI&_nc_zt=23&_nc_ht=scontent.faep9-1.fna&_nc_gid=vUJanVsgPPk_oFFbHmDqYg&oh=00_AfuwuTnxR064JhspO0To-_gf2om7BNsWgeN0U0GdAYoAwg&oe=698D2A68')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='tienda.emprendedor')),
            ],
        ),
    ]
