# Generated by Django 6.0.2 on 2026-02-07 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_producto_imagen_alter_producto_imagen_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprendedor',
            name='slug',
            field=models.SlugField(blank=True, help_text='Ej: capilares o zapatillas', null=True),
        ),
    ]
