# Generated by Django 6.0.2 on 2026-02-07 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_emprendedor_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprendedor',
            name='slug',
            field=models.SlugField(default='TEMPORAL1', help_text='Ej: capilares o zapatillas', unique=True),
            preserve_default=False,
        ),
    ]
