# Generated by Django 6.0.2 on 2026-02-07 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_alter_emprendedor_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emprendedor',
            options={'verbose_name': 'Emprendedor', 'verbose_name_plural': 'Emprendedores'},
        ),
        migrations.AddField(
            model_name='emprendedor',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
    ]
