# Generated by Django 6.0.2 on 2026-02-09 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0006_alter_producto_imagen_url_imagenproducto'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprendedor',
            name='telefono',
            field=models.CharField(blank=True, help_text='Ejemplo: 5491122334455 (Sin espacios ni el +)', max_length=20, null=True),
        ),
    ]
