# Generated by Django 6.0.2 on 2026-02-11 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0008_servicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='ubicacion',
            field=models.CharField(default='Consultar zona', help_text='Ej: Quilmes, Berazategui, etc.', max_length=100),
        ),
    ]
